
# Generated by CodiumAI

import pytest

class TestGetTotalRows:

    # Test with a CSV file containing multiple rows
    def test_get_total_rows_multiple_rows(self):
        # Create a temporary CSV file with multiple rows
        csv_data = [
            ['Name', 'Age', 'City'],
            ['John', '25', 'New York'],
            ['Jane', '30', 'Los Angeles'],
            ['Mike', '35', 'Chicago']
        ]
        with open('test.csv', 'w', newline='') as f:
            csvwriter = csv.writer(f)
            csvwriter.writerows(csv_data)

        # Call the get_total_rows function
        total_rows = get_total_rows('test.csv')

        # Assert that the total number of rows is correct
        assert total_rows == 3

        # Remove the temporary CSV file
        os.remove('test.csv')



class TestSplitCsv:
    # Split a CSV file with valid input and output directory
    def test_valid_input_and_output_directory(self):
        # Set up
        input_file_path = 'input.csv'
        row_limit = '100'
        output_dir = 'output'

        # Create input file
        with open(input_file_path, 'w', newline='') as input_file:
            csvwriter = csv.writer(input_file)
            csvwriter.writerow(['Name', 'Age'])
            csvwriter.writerow(['John', '25'])
            csvwriter.writerow(['Jane', '30'])
            csvwriter.writerow(['Mike', '35'])
            csvwriter.writerow(['Emily', '40'])

        # Call the function
        split_csv(input_file_path, row_limit, output_dir)

        # Check if output files are created
        assert os.path.isfile('output/input_part1.csv')
        assert os.path.isfile('output/input_part2.csv')

        # Check the content of the output files
        with open('output/input_part1.csv', 'r') as output_file:
            csvreader = csv.reader(output_file)
            assert next(csvreader) == ['Name', 'Age']
            assert next(csvreader) == ['John', '25']
            assert next(csvreader) == ['Jane', '30']

        with open('output/input_part2.csv', 'r') as output_file:
            csvreader = csv.reader(output_file)
            assert next(csvreader) == ['Name', 'Age']
            assert next(csvreader) == ['Mike', '35']
            assert next(csvreader) == ['Emily', '40']

        # Clean up
        os.remove(input_file_path)
        os.remove('output/input_part1.csv')
        os.remove('output/input_part2.csv')
        os.rmdir('output')

